### ISSUE TITLE
Adicionar site marinhoepinto.contamosconsigo.pt

### ISSUE THREAD

**Issue by EdSantos754** [paulasimoes/ArgumentsReformCopyright#10]
Algures em baixo, apenas na versão PT.
marinhoepinto.contamosconsigo.pt

**Comment by marado** [comment]
Já lá está, tanto na versão EN como PT:
"Open Letter to MEP Marinho e Pinto opposing Articles 13, 11, 4, 3" (EN)
"Carta Aberta a Marinho e Pinto contra os Artigos 13, 11, 4 e 3" (PT)
