### ISSUE TITLE
Vários

### ISSUE THREAD

**Issue by EdSantos754** [paulasimoes/ArgumentsReformCopyright#6]
**Títulos:** 
European Copyright Reform: decisions, decisions... So difficult decisions...
European Copyright Reform: decisions, decisions...

**Subtítulos:**
Desnecessários, acho. É mais giro quem vê a página começar a fazer scroll down e ver tudo aquilo do lado direito, e só quando chega lá abaixo percebe a coisa.

**Lado esquerdo:**
colocar aspas nas duas frases

**ideia**:
(não tenho a certeza, opina sff):
A única coisa que me está a fazer espécie nisto é que, como está, parece que estamos apenas a recorrer a argumentos de autoridade (citamos estudos académicos, cartas abertas de organizações, cartas de pessoas importantes, etc.), e não queria que essa fosse de todo a ideia principal disto.
Isso só se resolve se colocarmos do lado direito também os valores/princípios/direitos que estão ameaçados (apenas porque querem dar funding às duas cenas do lado esquerdo):

[antes dos links]
Freedom of Expression
Right to be Informed
Right to Access Information
General Monitoring
"Fair Uses"
Right to Quotation
Parody
Right to Education
Reinforcing monopolies
Specially from giant american techs
Restricting the sharing of news from trustful sources
Spread of fake news
(estou cansado, amanhã continuo...)

As demonstrated by:
[links]

Isto vai tornar aquela coluna ainda maior. :P 

**Link pro github?** (se alguem quiser ajudar/melhorar...)

**Comment by paulasimoes** [comment]
Done. Coloquei o primeiro título. Alguém mais vota no outro?
De resto, acho bem e já alterei. Coluna maior, melhor :-) (do ponto de vista da intenção, não necessariamente do ponto de vista técnico :-P)
